// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayevtzerqkqngapujjnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5ZXZ0emVycWtxbmdhcHVqam5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDc4NjEsImV4cCI6MjA2Mzg4Mzg2MX0.JJEcyz_pAFsbOEKUGpBJfwFvWc6sFuWtM_jmDN5020I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);